<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EQ55Q8H" failures="1" tests="3" name="Test" time="15.745" errors="0" timestamp="2025-06-06T16:10:12 IST">
  <testcase classname="extentReport.DemoExtentReport" name="chkLogo" time="0.068"/>
  <testcase classname="extentReport.DemoExtentReport" name="chkUrl" time="0.031">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.comm/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.comm/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at extentReport.DemoExtentReport.chkUrl(DemoExtentReport.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- chkUrl -->
  <testcase classname="extentReport.DemoExtentReport" name="chkPageTitle" time="0.0">
    <skipped/>
  </testcase> <!-- chkPageTitle -->
</testsuite> <!-- Test -->
